[package]
name = "pwnprob_setup"
version = "0.1.2"
edition = "2021"
description = "Create pwn prob docker file"
license = "MIT"

[dependencies]
clap = "4.0"
colored = "3.0.0"
md5 = "0.7"

[[bin]]
name = "pwnprob_setup"
path = "src/main.rs"